import type { Metadata } from "next";
import { Fraunces, Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Leaf Scan — Plant Disease Classifier",
  description:
    "Upload a leaf photo and get an instant disease classification.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${fraunces.variable} ${inter.variable} font-sans bg-canvas text-ink min-h-screen flex flex-col`}
      >
        <header className="border-b border-line">
          <div className="mx-auto max-w-5xl px-6 py-4 flex items-center justify-between">
            <Link href="/" className="font-serif text-lg text-forestDark">
              Leaf Scan
            </Link>
            <nav className="flex gap-6 text-sm text-ink">
              <Link href="/" className="hover:text-forest">
                Classify
              </Link>
              <Link href="/history" className="hover:text-forest">
                History
              </Link>
            </nav>
          </div>
        </header>

        <main className="mx-auto max-w-5xl px-6 py-10 flex-1 w-full">
          {children}
        </main>

        <footer className="border-t border-line">
          <div className="mx-auto max-w-5xl px-6 py-4 text-xs text-muted">
            Predictions are generated by a machine learning model and are not
            professional agronomic advice. Confirm with a local expert before
            treating a suspected disease.
          </div>
        </footer>
      </body>
    </html>
  );
}
