import type { Metadata } from "next";
import { Courier_Prime, Plus_Jakarta_Sans } from "next/font/google";
import AuthProvider from "@/components/AuthProvider";
import { MotionProvider } from "@/components/MotionProvider";
import { TopBar } from "@/components/TopBar";
import "./globals.css";

const courierPrime = Courier_Prime({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-courier-prime",
  display: "swap",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["400", "500"],
  subsets: ["latin"],
  variable: "--font-plus-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "PatraVyadhi",
  description:
    "Upload a leaf photo and get an instant disease classification.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${courierPrime.variable} ${plusJakartaSans.variable} font-sans bg-background text-text min-h-screen flex flex-col antialiased`}
      >
        <MotionProvider>
          <AuthProvider>
            <TopBar />
            <main className="mx-auto max-w-5xl w-full flex-1 px-4 sm:px-6 py-8 md:py-10 flex flex-col">
              {children}
            </main>
            <footer className="border-t border-leaf/20 bg-background">
              <div className="mx-auto max-w-5xl px-4 sm:px-6 py-4 text-xs text-text/70">
                Predictions are generated by a machine learning model and are not
                professional agronomic advice. Confirm with a local expert before
                treating a suspected disease.
              </div>
            </footer>
          </AuthProvider>
        </MotionProvider>
      </body>
    </html>
  );
}